base/urls.py
from django.urls import path
from . import views
from .views import LibraryList, BookDetail, BookCreate, BookUpdate, BookDelete, BorrowedBooksPage, BurrowBookView, ReturnBookView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', LibraryList.as_view(), name = 'books'),
    path('book/<int:pk>', BookDetail.as_view(), name = 'book'),
    path('book_add/', BookCreate.as_view(), name = 'book_add'),
    path('book_update/<int:pk>', BookUpdate.as_view(), name = 'book_update'),
    path('book_delete/<int:pk>', BookDelete.as_view(), name = 'book_delete'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', views.RegisterPage.as_view(), name='register'),
    path('my_books/', BorrowedBooksPage.as_view(), name='my_books'),
    path('borrow/', BurrowBookView.as_view(), name='book_borrow'),
    path('return/', ReturnBookView.as_view(), name='book_return'),


]

library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from languages_plus.models import Language
from countries_plus.models import Country
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    origin = models.ForeignKey(Country,on_delete=models.SET_NULL, null=True, blank=True, related_name='authors')
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} {self.surname}'



class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL,null=True, blank=True, related_name='books')
    publisher = models.CharField(max_length=100)
    pages = models.IntegerField()
    language = models.ForeignKey(Language,on_delete=models.SET_NULL, null=True, blank=True, related_name='books')
    description = models.TextField(blank=True, null=True)
    available = models.BooleanField(default=True)
    user = models.ManyToManyField(User, null=True, blank=True, related_name='borrowed_books')
    quantity = models.IntegerField(default=0)

   
    def belongs_to_user(self, user):
        return user in self.user.all()

    def __str__(self):
        return self.title
    

base/views.py
from urllib import request
from django.conf import LazySettings
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.urls import reverse_lazy
from .models import Book 
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin,AccessMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ImproperlyConfigured, ValidationError
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme, urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

class AdminRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

class LibraryList(LoginRequiredMixin, ListView):

    model = Book
    context_object_name = 'books'   
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Book.objects.filter(title__icontains=query)
        else:
           return Book.objects.all()
        
    def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      for book in context['books']:
         book.borrowed = book.belongs_to_user(self.request.user)
      return context
    
class BookDetail(LoginRequiredMixin, DetailView):
    model = Book
    context_object_name = 'book'   

class BookCreate(AdminRequiredMixin, 
LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')
    context_object_name = 'book_add'  
    template_name = 'base/book_add.html'

class BookUpdate(AdminRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')
    context_object_name = 'book_update'  
    template_name = 'base/book_update.html'

class BookDelete(AdminRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Book
    context_object_name = 'book'
    success_url = reverse_lazy('books')
    template_name = 'base/book_delete.html'

    

class CustomLoginView(LoginView):
  template_name = 'base/login.html'
  fields = '__all__'


  def get_success_url(self):
    return reverse_lazy ('books')
  

  def get(self, *args, **kwargs):
    if self.request.user.is_authenticated:
      return redirect('books')

    return super(CustomLoginView, self).get(*args, **kwargs)
  
class RegisterPage(FormView):
  template_name = 'base/register.html'
  form_class = UserCreationForm
  success_url = reverse_lazy('books')


  def form_valid(self, form):
    user = form.save()

    if user is not None:
      login(self.request, user)

    return super(RegisterPage, self).form_valid(form)
  

  def get(self, *args, **kwargs):
    if self.request.user.is_authenticated:
      return redirect('books')

    return super(RegisterPage, self).get(*args, **kwargs)


class BorrowedBooksPage(LoginRequiredMixin, ListView):

  model = Book
  context_object_name = 'books'   
  template_name = 'base/book_borrowed.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['books'] = Book.objects.filter(user__id=self.request.user.id)
    
    return context
  
  
class BurrowBookView(LoginRequiredMixin, View):
  def post(self, request):
    book_id = request.POST.get('book_id')
    book = Book.objects.get(pk=book_id)
    if book.quantity and request.user not in book.user.all():
       book.user.add(request.user)
       book.quantity -= 1
       book.save()
    return redirect(reverse_lazy('my_books'))
  

class ReturnBookView(LoginRequiredMixin, View):
  def post(self, request):
    book_id = request.POST.get('book_id')
    book = Book.objects.get(pk=book_id)
    if request.user in book.user.all():
       book.user.remove(request.user)
       book.quantity += 1
       book.save()
    return redirect(reverse_lazy('my_books'))
     

  

base/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Library of Georgia{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

base/templates/base/book_add.html
{% extends 'base.html' %}

{% block title %}Book Add{% endblock %}

{% block content %}
<div class="container">
    <h3>Book Add</h3>

    <a href="{% url 'books' %}">&lt;&lt; Go back</a>
    <br><br>

    <form method="POST" action="">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        {{ form.title }}
        
        <label for="id_author">Author:</label>
        {{ form.author }}
        
        <label for="id_publisher">Publisher:</label>
        {{ form.publisher }}
        
        <label for="id_pages">Pages:</label>
        {{ form.pages }}
        
        <label for="id_language">Language:</label>
        {{ form.language }}
        
        <label for="id_description">Description:</label>
        {{ form.description }}

        <label for="id_quantity">Quantity:</label>
        {{ form.quantity }}
        
        <input type="submit" value="Add Book">
    </form>
</div>
{% endblock %}

base/templates/base/book_borrowed.html
{% extends 'base.html' %}

{% block title %}Borrowed Books{% endblock %}

{% block content %}
<div class="container">
    <h1>Borrowed Books:</h1>

    <a href="{% url 'books' %}">&lt;&lt; Go back</a>
    <br><br><br>

    {% if books %}
        <table>
            <tr>
                <th>Title</th>
                <th>Action</th>
            </tr>
            {% for book in books %}
            <tr>
                <td>{{ book.title }}</td>
                <td>
                    <form method="post" action="/return/">
                        {% csrf_token %}
                        <input type="hidden" value="{{ book.id }}" name="book_id"/>
                        <button type="submit">Return</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>You do not have borrowed books.</p>
    {% endif %}
</div>
{% endblock %}

base/templates/base/book_delete.html
{% extends 'base.html' %}

{% block title %}Delete Book{% endblock %}

{% block content %}
<div class="container">
    <h3>Delete Book</h3>

    <a href="{% url 'books' %}">&lt;&lt; Go back</a>
    <br><br>

    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to remove the book from the Library?</p>
        <input type="submit" value="Delete" />
    </form>
</div>
{% endblock %}

base/templates/base/book_detail.html
{% extends 'base.html' %}

{% block title %}Book Details{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ book.title }}</h1>

    <div class="book-details">
        <p><span>Author:</span> {{ book.author }}</p>
        <p><span>Publisher:</span> {{ book.publisher }}</p>
        <p><span>Pages:</span> {{ book.pages }}</p>
        <p><span>Language:</span> {{ book.language }}</p>
    </div>

    <div class="book-description">
        <p><span>Description:</span></p>
        <p>{{ book.description }}</p>
    </div>
    <p><a href="{% url 'books' %}"><< Go Back</a></p>
</div>
{% endblock %}

base/templates/base/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library of Georgia</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% if request.user.is_authenticated %}
        <div class="header">
            <h1><a href="{% url 'books' %}">Library of Georgia</a></h1>
            
        </div>
        <p>Welcome {{ request.user }}!</p>
        <a href="{% url 'my_books' %}" id = "mybooks">My books</a>
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% else %} 
        <p><a href="{% url 'login' %}">Login</a></p> 
    {% endif %}

    <hr>

    
    
    {% if request.user.is_superuser %}
        <p><a href="{% url 'book_add' %}">Add a new book</a></p>
    {% endif %}
    
    <div class="search-container">
        <form method="GET" action="{% url 'books' %}">
            <input type="text" name="q" placeholder="Search books...">
            <button type="submit">Search</button>
        </form>
    </div>

    <h2>All books in Library:</h2>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Details</th>
                {% if request.user.is_superuser %}
                    <th>Edit</th>
                    <th>Delete</th>
                {% endif %}
                <th>Quantity</th>
                <th>Borrow</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td><a href="{% url 'book' book.id %}">Details >></a></td>
                    {% if request.user.is_superuser %}
                        <td><a href="{% url 'book_update' book.id %}">Edit</a></td>
                        <td><a href="{% url 'book_delete' book.id %}">Delete</a></td>
                    {% endif %}
                    <td>
                        {{ book.quantity }}
                    </td>
                    <td>
                        {% if book.borrowed or book.quantity == 0 %}
                            Borrowed
                        {% else %}
                        <form method="post" action="/borrow/">
                            {% csrf_token %}
                            <input type="hidden" value="{{ book.id }}" name="book_id"/>
                            <button type="submit">Borrow</button>
                        </form>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="{% if request.user.is_superuser %}5{% else %}3{% endif %}">No Books in Library</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

base/templates/base/book_update.html
{% extends 'base.html' %}

{% block title %}Update Book{% endblock %}

{% block content %}
<div class="container">
  <h1>Book Update Form</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Book</button>
  </form>

  <br>
  <p><a href="{% url 'books' %}"><< Go Back</a></p>
</div>
{% endblock %}

base/templates/base/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
  <h1>Login</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>

  <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
{% endblock %}

base/templates/base/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block content %}
  <h1>Register</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>

  <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
{% endblock %}